"""Add last_login and last_request_time to User's table

Revision ID: 08eb3dabde3e
Revises: 10cb0424aee2
Create Date: 2023-12-29 17:44:53.141682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08eb3dabde3e'
down_revision: Union[str, None] = '10cb0424aee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_request_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_request_time')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
