"""Add cascade deleting for User

Revision ID: 2eb5075af952
Revises: 08eb3dabde3e
Create Date: 2023-12-30 00:45:51.449573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb5075af952'
down_revision: Union[str, None] = '08eb3dabde3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_likes_user_id_fkey', 'user_likes', type_='foreignkey')
    op.drop_constraint('user_likes_post_id_fkey', 'user_likes', type_='foreignkey')
    op.create_foreign_key(None, 'user_likes', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_likes', type_='foreignkey')
    op.drop_constraint(None, 'user_likes', type_='foreignkey')
    op.create_foreign_key('user_likes_post_id_fkey', 'user_likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('user_likes_user_id_fkey', 'user_likes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
