"""Add cascade deleting for Post

Revision ID: 4c0bb813df0b
Revises: 2eb5075af952
Create Date: 2023-12-30 00:54:46.615097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0bb813df0b'
down_revision: Union[str, None] = '2eb5075af952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_owner_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_owner_id_fkey', 'posts', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
